### ISSUE TITLE
Error "Error resolving ImageStreamTag jboss-eap-xp1-openjdk11-openshift:1.0 in namespace nicolasduminil-dev: imagestreams.image.openshift.io "jboss-eap-xp1-openjdk11-openshift" not found" for field "from".

### ISSUE THREAD

**Issue by nicolasduminil** [jboss-container-images/jboss-eap-openshift-templates#58]
Hello,

Trying to follow the guide here, I'm experiencing the mentioned exception after having executed the command:

    $ oc process eap-s2i-build \
      -p APPLICATION_IMAGE=my-app \
      -p EAP_IMAGE=jboss-eap-xp1-openjdk11-openshift:1.0 \
      -p EAP_RUNTIME_IMAGE=jboss-eap-xp1-openjdk11-runtime-openshift:1.0 \
      -p EAP_IMAGESTREAM_NAMESPACE=$(oc project -q) \
      -p SOURCE_REPOSITORY_URL=https://github.com/jboss-developer/jboss-eap-quickstarts.git \
      -p SOURCE_REPOSITORY_REF=xp-1.0.x\
      -p CONTEXT_DIR=microprofile-config | oc create -f -

The build isn't done, as shown below:

    $ oc logs -f bc/my-eap-xp4-basic-build-artifacts
       error: no builds found for "my-eap-xp4-basic-build-artifacts"
    $ oc logs -f bc/my-eap-xp4-basic
      error: no builds found for "my-eap-xp4-basic"

And trying to execute the "start build" in the OpenShift console, displays:

    Error "Error resolving ImageStreamTag jboss-eap-xp1-openjdk11-openshift:1.0 in namespace nicolasduminil-dev: imagestreams.image.openshift.io "jboss-eap-xp1-openjdk11-openshift" not found" for field "from".

What did I miss here ?

Many thanks in advance.

Kind regards.

Nicolas

**Comment by jfdenise** [comment]
@nicolasduminil which template are you using?  Which XP release are you using? XP1 is old, it seems that the image jboss-eap-xp1-openjdk11-openshift:1.0 has not been imported in your namespace.

**Comment by nicolasduminil** [comment]
I'm following precisely the steps in this guide. So, I'm using the template below:

    $ oc replace --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-eap-openshift-templates/master/eap-s2i-build.yaml

And I'm using XP1 because this is what is documented here. Do you have any update for XP4 ?

**Comment by jfdenise** [comment]
The official XP4 doc is there: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html/using_jboss_eap_xp_4.0.0/index

**Comment by nicolasduminil** [comment]
Thanks. I tried that as well and got:

    $ oc new-app --template=eap-xp4-basic-s2i  -p EAP_IMAGE_NAME=jboss-eap-xp4-openjdk11-openshift:latest  -p EAP_RUNTIME_IMAGE_NAME=jboss-eap-xp4-openjdk11-runtime-openshift:latest  -p IMAGE_STREAM_NAMESPACE=eap-demo  -p SOURCE_REPOSITORY_URL=https://github.com/jboss-developer/jboss-eap-quickstarts  -p SOURCE_REPOSITORY_REF=xp-4.0.x  -p CONTEXT_DIR=microprofile-config
    --> Deploying template "nicolasduminil-dev/eap-xp4-basic-s2i" to project nicolasduminil-dev

     JBoss EAP XP 4.0 basic template
     ---------
     Example of an application based on JBoss EAP XP. For more information about using this template, see https://github.com/jboss-container-images/jboss-eap-openshift-templates/blob/eap-xp4/README.adoc

     A new JBoss EAP XP based application has been created in your project.

     * With parameters:
        * Application Name=eap-xp4-basic-app
        * EAP XP Image Name=jboss-eap-xp4-openjdk11-openshift:latest
        * EAP XP Runtime Image Name=jboss-eap-xp4-openjdk11-runtime-openshift:latest
        * Git Repository URL=https://github.com/jboss-developer/jboss-eap-quickstarts
        * Git Reference=xp-4.0.x
        * Context Directory=microprofile-config
        * Galleon layers=
        * Enable ExampleDS datasource=false
        * Queues=
        * Topics=
        * AMQ cluster password=XJuJlicX # generated
        * Github Webhook Secret=Xy2hVcvd # generated
        * Generic Webhook Secret=OmBE6fjU # generated
        * ImageStream Namespace=eap-demo
        * JGroups Cluster Password=lDq4WwpK # generated
        * Deploy Exploded Archives=false
        * Maven mirror URL=
        * Maven Additional Arguments=-Dcom.redhat.xpaas.repo.jbossorg
        * ARTIFACT_DIR=
        * MEMORY_LIMIT=1Gi

    W0120 16:42:38.632138    4265 newapp.go:1335] Unable to check for circular build input: Unable to check for circular build input/outputs: imagestreams.image.openshift.io "jboss-eap-xp4-openjdk11-openshift" is forbidden: User "nicolasduminil" cannot get resource "imagestreams" in API group "image.openshift.io" in the namespace "eap-demo"
    --> Creating resources ...
        service "eap-xp4-basic-app" created
        service "eap-xp4-basic-app-ping" created
        route.route.openshift.io "eap-xp4-basic-app" created
        imagestream.image.openshift.io "eap-xp4-basic-app" created
        imagestream.image.openshift.io "eap-xp4-basic-app-build-artifacts" created
        buildconfig.build.openshift.io "eap-xp4-basic-app-build-artifacts" created
        buildconfig.build.openshift.io "eap-xp4-basic-app" created
        deploymentconfig.apps.openshift.io "eap-xp4-basic-app" created
    --> Success
        Access your application via route 'eap-xp4-basic-app-nicolasduminil-dev.apps.sandbox.x8i5.p1.openshiftapps.com' 
        Build scheduled, use 'oc logs -f buildconfig/eap-xp4-basic-app-build-artifacts' to track its progress.
        Build scheduled, use 'oc logs -f buildconfig/eap-xp4-basic-app' to track its progress.
        Run 'oc status' to view your app.

As you can see, it raises again:

    W0120: nable to check for circular build input: Unable to check for circular build input/outputs: imagestreams.image.openshift.io "jboss-eap-xp4-openjdk11-openshift" is forbidden: User "nicolasduminil" cannot get resource "imagestreams" in API group "image.openshift.io" in the namespace "eap-demo"

Any idea ?

**Comment by jfdenise** [comment]
If you haven't imported the images in your namespace, don't set -p IMAGE_STREAM_NAMESPACE=eap-demo

**Comment by nicolasduminil** [comment]
Thanks again. I removed -p IMAGE_STREAM_NAMESPACE and, this way, it works much better. Now, I could see in the logs that it builds. But trying to get the endpoint:

    $ oc get route
    NAME                HOST/PORT                                                                     PATH   SERVICES            PORT    TERMINATION       WILDCARD
    eap-xp4-basic-app   eap-xp4-basic-app-nicolasduminil-dev.apps.sandbox.x8i5.p1.openshiftapps.com          eap-xp4-basic- app   <all>   edge/Redirect   None
    nicolas@nicolas-XPS-13-9360:~$ curl http://eap-xp4-basic-app-nicolasduminil-dev.apps.sandbox.x8i5.p1.openshiftapps.com/microprofile-config/config/value
    nicolas@nicolas-XPS-13-9360:~$

doesn't seem to work as it doesn't return the expected string.

And another question: what should I have done previously such that the images be imported in my namespace ? I followed the guide here. Is there anything missing or to be amended ?

**Comment by jfdenise** [comment]
To import the image in your namespace:
oc import-image jboss-eap-7/eap-xp4-openjdk11-openshift-rhel8:4.0-29 --from=registry.redhat.io/jboss-eap-7/eap-xp4-openjdk11-openshift-rhel8:4.0-29 --confirm
BTW, the source of truth for EAP XP is the redhat doc I linked.
Possibly try with https://eap-xp4-basic-app-nicolasduminil-dev.apps.sandbox.x8i5.p1.openshiftapps.com/microprofile-config/config/value
Thank-you.

**Comment by nicolasduminil** [comment]
I followed the instructions in the doc you've linked and it doesn't mention at any moment the "oc import-image" statement. Does it mean that the doc is outdated or inaccurate ? And using HTTPS instead of HTTP doesn't work neither.

**Comment by nicolasduminil** [comment]
However, it works in browser ...
